### PR TITLE
Fix Throttling

### PR DESCRIPTION
**Pull request by clyang82**
Fixed 2 issues:
1. https://github.com/observatorium/operator/issues/12
2. https://github.com/observatorium/deployments/issues/319

When calling `c.getAPIResource(apiVersion, kind)` which calls `c.kclient.Discovery().ServerResources()` to get all APIResources. if one of apiresource is not ready, `locutus` stops working.

Each action will call `c.kclient.Discovery().ServerResources()` which leads to throttling. use `ServerResourcesForGroupVersion` instead.

### CODE REVIEW

**Comment by metalmatze** [comment]
Generally sounds good. I haven't tried or seen this myself though. :)

**Review by brancz — APPROVED** [review]
Makes sense, I can see how this can easily happen if there are lots of objects to deploy.

**Comment by clyang82** [comment]
Thanks @brancz and @metalmatze

**Pull request merged**
